services:
  fintrack-api:
    build:
      context: .
      dockerfile: src/services/FinTrack-api/fintrack-api/Dockerfile

    container_name: fintrack-api
    image: fintrack-api:latest

    ports:
      - "5000:5000"

    env_file:
      - .env
    networks:
      - fintrack-network

networks:
  fintrack-network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/24
