services:
  fintrack-api:
    build:
      context: .
      dockerfile: src/services/FinTrack-api/fintrack-api/Dockerfile

    container_name: fintrack-api
    image: fintrack-api:latest

    ports:
      - "5000:5000"

    env_file:
      - .env

    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      DATABASE_CONN_STRING: ${DATABASE_CONN_STRING}
      AUTH0_Authority: ${AUTH0_Authority}
      AUTH0_Audience: ${AUTH0_Audience}
      JWT_SECRET: ${JWT_SECRET}
