#   docker network create fintrack-network --subnet=192.168.100.0/24

services:
  fintrack-api:
    build:
      context: .
      dockerfile: src/services/FinTrack-api/fintrack-api/Dockerfile

    container_name: fintrack-api
    image: fintrack-api:latest

    ports:
      - "5000:5000"

    env_file:
      - .env
    networks:
      - fintrack-network # Connects to the fintrack-network
    depends_on:
      - fintrack-database-server # Wait for the database to be ready

  fintrack-database-server:
    image: mariadb
    volumes:
      - ${DATABASE_VOLUME}:/var/lib/mysql
    container_name: fintrack-database-server
    ports:
      - "3306:3306"
    env_file:
      - .env
    networks:
      - fintrack-network # Connects to the fintrack-network

networks:
  fintrack-network:
    external: true
    name: fintrack-network
